#!/usr/bin/python3.8

import scapy.all as scapy

def get_mac(ip):
	req = scapy.ARP(pdst=ip)
	broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
	packet = broadcast/req
	ans = scapy.srp(packet, timeout=1, verbose=False)[0]
	return ans[0][1].hwsrc

def sniff(interface):
	scapy.sniff(iface=interface, store=False, prn=process_packet)

def process_packet(packet):
	if packet.haslayer(scapy.ARP) and packet[scapy.ARP].op==2:
		try:
			real_mac = get_mac(packet[scapy.ARP].psrc)
			response_mac = packet[scapy.ARP].hwsrc
			if real_mac != response_mac:
				print('under attack!!')
		except:
			pass

get_mac('10.14.143.1/24')